AWSTemplateFormatVersion: '2010-09-09'
Description: 'CRPBot S3 Buckets for market data, backups, and logs'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

Resources:
  # Market Data Bucket
  MarketDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'crpbot-market-data-${Environment}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveOldData
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: GLACIER
              - TransitionInDays: 365
                StorageClass: DEEP_ARCHIVE

  # Backups Bucket with Versioning
  BackupsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'crpbot-backups-${Environment}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveBackups
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: GLACIER

  # Logs Bucket
  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'crpbot-logs-${Environment}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 365

  # IAM Role for S3 Access
  S3AccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'crpbot-s3-access-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3BucketAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub '${MarketDataBucket}/*'
                  - !Sub '${BackupsBucket}/*'
                  - !Sub '${LogsBucket}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${MarketDataBucket}'
                  - !Sub 'arn:aws:s3:::${BackupsBucket}'
                  - !Sub 'arn:aws:s3:::${LogsBucket}'

Outputs:
  MarketDataBucketName:
    Description: Name of the market data bucket
    Value: !Ref MarketDataBucket
    Export:
      Name: !Sub '${AWS::StackName}-MarketDataBucket'

  BackupsBucketName:
    Description: Name of the backups bucket
    Value: !Ref BackupsBucket
    Export:
      Name: !Sub '${AWS::StackName}-BackupsBucket'

  LogsBucketName:
    Description: Name of the logs bucket
    Value: !Ref LogsBucket
    Export:
      Name: !Sub '${AWS::StackName}-LogsBucket'

  S3AccessRoleArn:
    Description: ARN of the S3 access role
    Value: !GetAtt S3AccessRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-S3AccessRole'