AWSTemplateFormatVersion: '2010-09-09'
Description: 'CRPBot Secrets Manager for API keys and credentials'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]

Resources:
  # Coinbase API Secret
  CoinbaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'crpbot/coinbase-api/${Environment}'
      Description: 'Coinbase API credentials for CRPBot'
      SecretString: !Sub |
        {
          "api_key": "REPLACE_WITH_YOUR_COINBASE_API_KEY_NAME",
          "private_key": "REPLACE_WITH_YOUR_COINBASE_PRIVATE_KEY_PEM"
        }
      Tags:
        - Key: Project
          Value: crpbot
        - Key: Environment
          Value: !Ref Environment

  # Telegram Bot Secret
  TelegramSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'crpbot/telegram-bot/${Environment}'
      Description: 'Telegram bot credentials for CRPBot'
      SecretString: !Sub |
        {
          "bot_token": "REPLACE_WITH_YOUR_TELEGRAM_BOT_TOKEN",
          "chat_id": "REPLACE_WITH_YOUR_TELEGRAM_CHAT_ID"
        }
      Tags:
        - Key: Project
          Value: crpbot
        - Key: Environment
          Value: !Ref Environment

  # FTMO Account Secret
  FTMOSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'crpbot/ftmo-account/${Environment}'
      Description: 'FTMO account credentials for CRPBot'
      SecretString: !Sub |
        {
          "login": "REPLACE_WITH_YOUR_FTMO_LOGIN",
          "password": "REPLACE_WITH_YOUR_FTMO_PASSWORD",
          "server": "REPLACE_WITH_YOUR_FTMO_SERVER"
        }
      Tags:
        - Key: Project
          Value: crpbot
        - Key: Environment
          Value: !Ref Environment

  # IAM Role for Secrets Access
  SecretsAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'crpbot-secrets-access-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource:
                  - !Ref CoinbaseSecret
                  - !Ref TelegramSecret
                  - !Ref FTMOSecret

Outputs:
  CoinbaseSecretArn:
    Description: ARN of Coinbase API secret
    Value: !Ref CoinbaseSecret
    Export:
      Name: !Sub '${AWS::StackName}-CoinbaseSecretArn'

  TelegramSecretArn:
    Description: ARN of Telegram bot secret
    Value: !Ref TelegramSecret
    Export:
      Name: !Sub '${AWS::StackName}-TelegramSecretArn'

  FTMOSecretArn:
    Description: ARN of FTMO account secret
    Value: !Ref FTMOSecret
    Export:
      Name: !Sub '${AWS::StackName}-FTMOSecretArn'

  SecretsAccessRoleArn:
    Description: ARN of secrets access role
    Value: !GetAtt SecretsAccessRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SecretsAccessRoleArn'