-- V4 Monitoring System Database Schema
-- PostgreSQL 13+

-- Signals generated by ML
CREATE TABLE IF NOT EXISTS signals (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    coin VARCHAR(20) NOT NULL,
    direction VARCHAR(4) NOT NULL CHECK (direction IN ('LONG', 'SHORT')),
    confidence FLOAT NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    entry_low FLOAT NOT NULL,
    entry_high FLOAT NOT NULL,
    stop_loss FLOAT NOT NULL,
    take_profit FLOAT NOT NULL,
    position_size FLOAT NOT NULL,
    signal_type VARCHAR(20),
    reasoning TEXT,
    status VARCHAR(20) DEFAULT 'ready' CHECK (status IN ('ready', 'paused', 'expired', 'executed')),
    tier INT CHECK (tier IN (1, 2, 3)),
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_signals_timestamp ON signals(timestamp DESC);
CREATE INDEX idx_signals_status ON signals(status);
CREATE INDEX idx_signals_coin ON signals(coin);

-- Trades executed and tracked
CREATE TABLE IF NOT EXISTS trades (
    id SERIAL PRIMARY KEY,
    signal_id INT REFERENCES signals(id),
    coin VARCHAR(20) NOT NULL,
    direction VARCHAR(4) NOT NULL,
    entry_price FLOAT NOT NULL,
    exit_price FLOAT,
    entry_time TIMESTAMP NOT NULL,
    exit_time TIMESTAMP,
    win BOOLEAN,
    pnl FLOAT,
    pnl_percent FLOAT,
    exit_reason VARCHAR(50),
    bybit_order_id VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_trades_entry_time ON trades(entry_time DESC);
CREATE INDEX idx_trades_coin ON trades(coin);

-- Performance snapshots
CREATE TABLE IF NOT EXISTS performance_snapshots (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    win_rate_last_20 FLOAT,
    pnl_daily FLOAT,
    pnl_weekly FLOAT,
    pnl_monthly FLOAT,
    sharpe_ratio FLOAT,
    max_drawdown FLOAT,
    ece FLOAT,
    consecutive_losses INT,
    total_trades INT,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_perf_timestamp ON performance_snapshots(timestamp DESC);

-- Controller status (traffic light)
CREATE TABLE IF NOT EXISTS controller_status (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    status VARCHAR(10) NOT NULL CHECK (status IN ('green', 'yellow', 'red')),
    message TEXT NOT NULL,
    position_multiplier FLOAT NOT NULL CHECK (position_multiplier >= 0 AND position_multiplier <= 1),
    triggered_by VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_controller_timestamp ON controller_status(timestamp DESC);

-- Alerts sent
CREATE TABLE IF NOT EXISTS alerts_sent (
    id SERIAL PRIMARY KEY,
    alert_type VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    sent_at TIMESTAMP NOT NULL,
    delivered BOOLEAN DEFAULT FALSE,
    channel VARCHAR(20) CHECK (channel IN ('telegram', 'email')),
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_alerts_sent_at ON alerts_sent(sent_at DESC);

-- Per-signal-type performance
CREATE TABLE IF NOT EXISTS signal_type_performance (
    id SERIAL PRIMARY KEY,
    signal_type VARCHAR(20) NOT NULL,
    period VARCHAR(20) NOT NULL,
    win_rate FLOAT,
    trade_count INT,
    avg_pnl FLOAT,
    updated_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(signal_type, period)
);

-- Per-coin performance
CREATE TABLE IF NOT EXISTS coin_performance (
    id SERIAL PRIMARY KEY,
    coin VARCHAR(20) NOT NULL,
    period VARCHAR(20) NOT NULL,
    win_rate FLOAT,
    trade_count INT,
    avg_pnl FLOAT,
    tier INT,
    updated_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(coin, period)
);

-- Initial controller status (green)
INSERT INTO controller_status (timestamp, status, message, position_multiplier, triggered_by)
VALUES (NOW(), 'green', 'System initialized - all checks passed', 1.0, 'system_init')
ON CONFLICT DO NOTHING;

COMMIT;
